language: python
python: 2.7
sudo: false
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
install:
  - pip install tox
script:
  - tox --version
  - python setup.py test --tox-args="-e $TOX_ENV"
